### ISSUE TITLE
timestamp issue with SQL server

### ISSUE THREAD

**Issue by apeesel** [GeoffMontee/tds_fdw#13]
My table definition reads:

CREATE foreign TABLE mssql_location_tender(
 Location_Tender_ID bigint,
 LocationID int,
 TenderID int,
SnapTenderID int,
SnapTenderName varchar(50),
 AddedBy int,
 AddedDate timestamp,
UpdatedBy varchar(100),
UpdatedDate timestamp,
ReviewedBy varchar(100),
 ReviewedDate timestamp
 ) server mssql_db04 options (database 'Mapper_New', table 'Location_Tender');

When I try to select from the table I get the following:
gmpoc=# select * from mssql_location_tender limit 10;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'master'., Server: DB04, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 1, Msg: Changed database context to 'Mapper_New'., Server: DB04, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'master'., Server: DB04, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 1, Msg: Changed database context to 'Mapper_New'., Server: DB04, Process: , Line: 1, Level: 0
ERROR:  invalid input syntax for type timestamp: "Jan 21 2013 09:39:36:523AM"

I have 2 questions:
1) I cannot select from any table that has a column defined as a datetime in SQL and timestamp in postgres.  I've tried using a query instead of a table definition as well with a cast function and that doesn't work either.  How can I use timestamp with this wrapper?
2) How can I get rid of the DB-Library notice?

Thanks

**Comment by joefromct** [comment]
Hi,

I've been following this thread as i'm having the same issue. 

I've updated the /etc/locales.conf and still have the formatting error:
    < 2015-01-08 13:14:29.311 EST >ERROR:  invalid input syntax for type timestamp: "Dec 24 2014 01:36:58:087PM"

I think (not sure) this could be a problem with the %z?  man 3 strftime shows %z reserved for something other than miliseconds:  http://linux.die.net/man/3/strftime 

Maybe strftime added a %z that confuses something?

Is there anyway to truncate the miliseconds?  I could do that too i think... would really like to get this working.

**Comment by joefromct** [comment]
Ok, apologies but i restarted my instance after the modification to locales.conf and all seems to work now.

Also, i noticed i missed something in the documentation for freetds:

> If your system's strftime(3) does employ %z for its own use, it will not be given that chance by 
> FreeTDS. FreeTDS will consume the %z for its milliseconds needs, and will not pass it on to 
> strftime(3).

Thanks everyone for your help.

**Comment by tomhath** [comment]
I had to set the date format in locales.conf rather than freetds.conf 

The locales.conf file seems to be deprecated, but the version of freetds I have ignored the date format setting in freetds.conf

**Comment by GeoffMontee** [comment]
I posted about this on the FreeTDS mailing list. In particular, I asked if they would consider changing the default date format in the next release. I'll watch for a response.

http://lists.ibiblio.org/pipermail/freetds/2015q2/029275.html

**Comment by tomhath** [comment]
Thanks. The tds_fdw wrapper works great for us, really a nice capability to
have available.

**Comment by GeoffMontee** [comment]
I hope to eventually remove the requirement to change `locales.conf`. See issue #28.

**Comment by GeoffMontee** [comment]
Issue #28 has a fix out now.

**Comment by GeoffMontee** [comment]
Fixed in v1.0.4.

**Comment by DrLove73** [comment]
I use PostgreSQL 10 on CentOS 7 with freetds 1.1.6-0.el7,  postgresql-10-tds_fdw  2.0.0-alpha.3.2.el7 from tds_fdw repository and I just had to change ":" to "." in /etc/locales.conf to get date from MSSQL 2008R2 "date" column instead of `ERROR: invalid input syntax for type timestamp:` .
Previous to this, I had to add 
```
        tds version = 7.3
        client charset = UTF-8

```
to /etc/freetds.conf to get proper letters (Serbian_Latin collation).
If you need more data please tell me what you need.

**Comment by rrebollo** [comment]
I thing this behaviour is back, at least in current debian jessie pakages.

**Comment by okkof2000** [comment]
i meet the same trouble in win10, how to change ":" to "."  in windows? i can not find the  freetds.conf

**Comment by DrLove73** [comment]
> i meet the same trouble in win10, how to change ":" to "." in windows? i can not find the freetds.conf

Mine (on Windows VM) is in c:\Windows\System32\

**Comment by okkof2000** [comment]
thanks for your reply, 
i used the postgresql12.6 for windows
I download the  tds_fdw for windows from https://github.com/tds-fdw/tds_fdw/issues/53#issuecomment-626329771 
i just past all the files in the pg folder,
after IMPORT FOREIGN SCHEMA,i can see the data except the  timestamp data,
it show that 
ERROR: invalid input syntax for type timestamp: ""Jan 03 2020 08:43:00:000PM""
i have search all the filessystem ,can not found the freetds.conf or locales.conf
i create a  locales.conf ,and paste it into 
c:\Windows\System32\
C:\Users\username\AppData\Roaming\freetds\
but it is not work
what should i do next?
thanks again

**Comment by axellpadilla** [comment]
this still a problem
