### ISSUE TITLE
Invalid count returned.

### ISSUE THREAD

**Issue by shulcsm** [GeoffMontee/tds_fdw#15]
Hello, i'm using mssql server and freetds 7.0
This https://github.com/GeoffMontee/tds_fdw/blob/master/src/tds_fdw.c#L905 returns -1 and breaks costs. I found out https://gitorious.org/freetds/freetds/source/d78804636aef4562966e89a8d57aec7bea98cc3b:src/dblib/dblib.c#L2782 exists, but i'm clueless about the topic. Let me know if i can give you any more information.

**Comment by GeoffMontee** [comment]
I found out today that there's a DB-Library function called [dbsetopt](http://www.freetds.org/reference/a00341.html#ga9d660d278f3f58871b4086c0e175f4c6). [Some options are](https://github.com/FreeTDS/freetds/blob/59f49d2fd181e9669b56815bce48ca1e64b790ca/include/sybdb.h#L367):

* `DBESTIMATE`
* `DBNOEXEC`

I wonder if these options can somehow be used to get an estimate of executing the query without actually executing the query.

I hope to look into this soon and ask about this on the FreeTDS mailing list if I can't figure it out on my own.

Also related to the bad `dbcount()` return, I wonder if these options are related to that somehow?

* `DBNOCOUNT`
* `DBROWCOUNT`

I also wonder if the [`dbiscount()`](http://www.freetds.org/reference/a00341.html#ga6ba2a7f18cb76d24776e45fd71141494) is related to that.

**Comment by GeoffMontee** [comment]
I'm not sure why `dbcount` is returning -1, but I've fixed this problem by returning `rows_increment` rather than `rows_report` when `dbicount()` returns `0`.

Commit: https://github.com/GeoffMontee/tds_fdw/commit/fb5b96d32b6c7dabfafee8c78ca6437b57d7f1ef

I do want to improve how tds_fdw estimates its costs. However, that change will probably be more intrusive.

**Comment by GeoffMontee** [comment]
By the way, I've added the ability to set the option `row_estimate_method` to the value `showplan_all` on a foreign table in the latest commit. This will use [MS SQL Server's SET SHOWPLAN_ALL](https://msdn.microsoft.com/en-us/library/ms187735.aspx) to get row estimations. This means the query no longer has to get executed twice.

Commit: https://github.com/GeoffMontee/tds_fdw/commit/e4d830faf668baa308572afcb27b3439078bfb37

**Comment by GeoffMontee** [comment]
Fixed in version 1.0.2.

**Comment by shulcsm** [comment]
Finally got to trying it out. It works. Thanks!
