### ISSUE TITLE
Postgres 9.4

### ISSUE THREAD

**Issue by apeesel** [GeoffMontee/tds_fdw#17]
Is there a version for postgres 9.4 on the horizon?

April

**Comment by GeoffMontee** [comment]
I think the current release should work on 9.4 with the same code used to work on 9.3. Have you tried it?

**Comment by apeesel** [comment]
I'm on CentOS an yum install instructions say 9.3.  I'll give it a try and see what it does.

**Comment by GeoffMontee** [comment]
Right. Only the version numbers should change for 9.4. If you were installing everything from scratch on CentOS 6, it would look something like:

```
sudo yum install epel-release
sudo yum install freetds freetds-devel
wget http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm
sudo rpm -ivh pgdg-centos94-9.4-1.noarch.rpm
sudo yum install postgresql94 postgresql94-server postgresql94-libs postgresql94-devel
git clone https://github.com/GeoffMontee/tds_fdw.git
cd tds_fdw
PATH=/usr/pgsql-9.4/bin:$PATH make USE_PGXS=1
sudo PATH=/usr/pgsql-9.4/bin:$PATH make USE_PGXS=1 install
```

Let me know if anything doesn't work.

**Comment by apeesel** [comment]
It worked - thanks!

**Comment by GeoffMontee** [comment]
Great! I'm glad that worked for you.
