### ISSUE TITLE
Empty strings are selected as NULL

### ISSUE THREAD

**Issue by shawjef3** [GeoffMontee/tds_fdw#18]
Hello,
In SQL Server 2008 R2 I have some nvarchar fields that are nullable. When they are empty strings, they are selected as NULL in PostgreSQL.

Jeff

**Comment by shawjef3** [comment]
Sorry, this is a bug in freetds that was found in 2006 and apparently never fixed.

http://sourceforge.net/p/freetds/bugs/25/

**Comment by shawjef3** [comment]
After reading the thread more closely, they used stock freetds 0.63 and fixed the php library. I'll look at tds fdw to see if I can find a similar problem.

**Comment by shawjef3** [comment]
OK, it's not a problem with tds_fdw. I set my tds version to auto from 7.2, and empty nvarchars are coming through as empty varchars.

**Comment by shawjef3** [comment]
Setting the tds version to auto caused long nvarchars to be truncated to 255 characters. Setting the tds version to 8.0 fixed the truncation, but once again empty strings are being selected as NULL.

**Comment by GeoffMontee** [comment]
http://lists.ibiblio.org/pipermail/freetds/2015q2/029389.html

**Comment by GeoffMontee** [comment]
Fixed: https://github.com/GeoffMontee/tds_fdw/commit/b5f678cded099f9231473c520cf1dbe8363a470a

**Comment by GeoffMontee** [comment]
Fixed in 1.0.3.
