### ISSUE TITLE
Column type date mapping

### ISSUE THREAD

**Issue by sumariva** [GeoffMontee/tds_fdw#21]
Would be nice to have automatic discovery/mappings/conversion for (:?small)datetime fields.
Maybe add a new option for default date conversion field for each table column.

column definition OPTION ( 'dateformat', 'Mon DD YYYY HH:MI:SS:MSAM' )

With this new option, then the C code executor could inquiry postgresql foreign table definition and invoke
the postgresql to_date('Apr 10 2015 05:02:00:000AM', 'Mon DD YYYY HH:MI:SS:MSAM' ) to convert mssql format to native postgresql format.

Suggesting this because when creating a foreign table with date field, cause invalid data error during execution. And adding this option would make conversion as simple as definition the format masks.

**Comment by GeoffMontee** [comment]
The date format issue is actually related to FreeTDS. I'm hoping the FreeTDS developers are willing to change the default date format to something more standard. See this thread in issue #13:

https://github.com/GeoffMontee/tds_fdw/issues/13

**Comment by sumariva** [comment]
According to the following site
http://www.sql-server-helper.com/sql-server-2008/sql-server-2008-date-format.aspx
 the problem with dates is the mismatch between standard format conversion between postgres and mssql.
MSSQL uses the milliseconds suffix - :000AM - that is not recognized by implicit cast on postgres.

I suggesting that the foreign wrapper be enchanced with the ability to do automatic translation between standard mssql types and postgresql types. Following your references on issue #13 I see the following maps that should be handled by the driver:

<table>
<caption>Automatic foreign driver type translation</caption>
<tr>
<th>pgsql type<th> mssql type<th>column option
</tr>
<tr>
<td>time<td>time<td>none required
</tr>
<tr>
<td>date<td>date<td>none required
</tr>
<tr>
<td>timestamp<td>smalldatetime<td>dateformat 'format expected by postgresql to_char'
</tr>
<tr>
<td>timestamp<td>datetime<td>dateformat 'format expected by postgresql to_char'
</tr>
<tr>
<td>timestamp<td>datetime2<td>dateformat 'format expected by postgresql to_char'
</tr>
<tr>
<td>timestamptz<td>datetimeoffset<td>dateformat 'format expected by postgresql to_char'
</tr>
</table>

**Comment by GeoffMontee** [comment]
My point is that MS SQL Server's date format seems almost irrelevant to this conversation, since FreeTDS does its own transformation (based on the value of "date format") before tds_fdw ever sees the data. My hope is that FreeTDS will change the default "date format" value to something a little more standard, which would make this problem go away for most people.

If that doesn't work out, maybe a column option would be worthwhile.

**Comment by shawjef3** [comment]
If you change the default date format in locales.conf to have a . instead of a : for the fractional seconds separator, it works.

**Comment by GeoffMontee** [comment]
I don't really like the fact that users have to edit `locales.conf` to make this work. It looks like it would be easy to use a DB-Library function like [`dbdatecrack()`](http://www.freetds.org/reference/a00341.html#ga3cfb1c1c8c50a09a9ac4d75800547f7a) to pull out the individual parts. Then I could just use `make_timestamp()` and the other similar functions to build the `timestamp`, `date`, or `time` columns.

I haven't ever tried to call PostgreSQL's SQL functions from C code, but I think it would be worth it to learn how to do so.

**Comment by GeoffMontee** [comment]
Rather than using a foreign server, table, or column option, I think I'd prefer the `dbdatecrack()` method, if I can make it work. If users want a specific format, they can use [`to_char()`](http://www.postgresql.org/docs/9.4/static/functions-formatting.html).

Added that task as issue #28.

**Comment by GeoffMontee** [comment]
Issue #28 has a fix out now.
