### ISSUE TITLE
How to suppress "NOTICE:  DB-Library notice:" 

### ISSUE THREAD

**Issue by tohio** [GeoffMontee/tds_fdw#22]
Hi Geoff,
I have just configured the tds_fdw, and it is working just fine. My question is, how do I suppress the message below. Is there a flag in the create server command that does this? Thanks

NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'master'., Server: WD ...
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 1, Msg: Changed database context to 'test'., Server: ...
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'master'., Server: ..
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 1, Msg: Changed database context to 'test'., Server: ..
NOTICE:  No more rows

**Comment by GeoffMontee** [comment]
Hi @tohio. There is no way to suppress these notices at the moment. However, that is a feature I'd like to add when I can find time to add it.

**Comment by tohio** [comment]
@GeoffMontee Thanks for the quick response, I look forward to the update. I will suppress the notices messages using client_messages  parameter.

Also, have you added the ability to write to foreign tables? Thanks again

**Comment by GeoffMontee** [comment]
Fixed: https://github.com/GeoffMontee/tds_fdw/commit/720ae2491b37f03e5b7a89778571c71408501b6b

See the description of the new *msg_handler* [foreign server option](https://github.com/GeoffMontee/tds_fdw/blob/master/ForeignServerCreation.md). It will default to a value of *blackhole*.

There's no write support yet. That is #9.

**Comment by GeoffMontee** [comment]
Fixed in 1.0.3.
