### ISSUE TITLE
Use DB-Library's dbdatecrack() and PostgreSQL's make_timestamp() to make changes to locales.conf unnecessary

### ISSUE THREAD

**Issue by GeoffMontee** [GeoffMontee/tds_fdw#28]
I don't really like the fact that users have to edit the default `locales.conf` to allow PostgreSQL to understand timestamp strings returned by FreeTDS.

It looks like it would be easy to use a DB-Library function like [`dbdatecrack()`](http://www.freetds.org/reference/a00341.html#ga3cfb1c1c8c50a09a9ac4d75800547f7a) to pull out the individual parts of `timestamp`, `date` and `time` columns.. Then I could just use [`make_timestamp()`](http://www.postgresql.org/docs/9.4/static/functions-datetime.html) and the other similar functions to build the `timestamp`, `date`, or `time` columns.

I should probably put this code in [`tdsConvertToCString()`](https://github.com/GeoffMontee/tds_fdw/blob/d9e2f438d55f5709cca06244fa81ee23b36b8e0e/src/tds_fdw.c#L922).

I haven't ever tried to call PostgreSQL's SQL functions (like make_timestamp) from C code, but I think it would be worth it to learn how to do so.

**Comment by sumariva** [comment]
That would be nice.
I assume that freetds will receive the binary value from server, from 3 to 8 bytes as defined by the column type for date/time types.
Avoid conversion from text string to reduce network traffic if possible.
For larger results, maybe a prepared postgresql statement for date transformation could speed up successive row construction for the result.

**Comment by GeoffMontee** [comment]
A special conversion has been added for SQL Server and Sybase's `DATETIME` type using DB-Library's `dbdatecrack()` and `make_timestamp()`.

https://github.com/GeoffMontee/tds_fdw/commit/f4cab847db183f8da030260008ed28fe15d76edc

**Comment by GeoffMontee** [comment]
I just realized that the current implementation doesn't properly set the milliseconds value. I'll try to fix that tomorrow.

**Comment by GeoffMontee** [comment]
I added millisecond support, and fixed some other minor things.

https://github.com/GeoffMontee/tds_fdw/commit/5389eedeec3275d4ea6624357872a1f597c8374f

**Comment by GeoffMontee** [comment]
Fixed in v1.0.4.

**Comment by gavinwahl** [comment]
Can you do this for dates too? I'm getting errors like

` invalid input syntax for type date: "Aug 25 2010 12:00:00:AM"`
