### ISSUE TITLE
Warning on the foreign server generates a postgresql error

### ISSUE THREAD

**Issue by Torgan** [GeoffMontee/tds_fdw#31]
Hello,

I'm having an issue when accessing a MSSQL server and getting some corrupted UTF16 data. The server issues a warning that is transformed as an postgres error :

```
ERROR:  DB-Library error: DB #: 2403, DB Msg: Some character(s) could not be converted into client's character set.  Unconverted bytes were changed to question marks ('?'), OS #: 0, OS Msg: Success, Level: 4
```

I wasn't able to clear the data in the query (tried using nvarchar conversion, COLLATE and xml-related methods, to no avail).

I have been playing with configuration about charset, version, and even tried use utf_16 = yes. However, once again, I had no success with it.

Would it be possible not to convert foreign data warnings into errors ?

Thanks in advance

**Comment by GeoffMontee** [comment]
Hi @Torgan,

That error is raised by FreeTDS.

When using tds_fdw, there are a few different encodings that you have to keep in mind. If any of them are incompatible, you could run into issues.

1.) The encoding of the remote MS SQL Server column.

2.) The encoding of the local PostgreSQL database.

You should make this encoding compatible with the encoding of the MS SQL Server column.

3.) The encoding used in the tds protocol between the remote and local servers.

If your remote MS SQL Server database uses Unicode encodings, you should set `tds_version` to 7.0 or higher. In that case, this is always UCS-2.

4.) The encoding used by your PostgreSQL client.

To determine what encoding your client is using, type:

```
SHOW client_encoding
```

To change it to UTF-8 for your current session, you could do:

```
SET NAMES 'UTF8';
```

5.) The encoding that FreeTDS uses to convert the data off the wire into for the client.

FreeTDS may or may not select your PostgreSQL client's encoding for this. If it doesn't, set the `client charset` variable in freetds.conf.

For starters, could you try to make sure the following is true for your configuration:

1.) `tds_version` is set to 7.0 or higher in freetds.conf.
2.) `client charset` is set to utf-8 in freetds.conf.
3.) Your local PostgreSQL databases uses 'UTF8' encoding.
4.) Your PostgreSQL client uses 'UTF8' encoding.
