### ISSUE TITLE
Support PostgreSQL 9.5

### ISSUE THREAD

**Issue by mc-soi** [GeoffMontee/tds_fdw#33]
This patch adds support for PostgreSQL 9.5 by adding a required parameter:
https://gist.github.com/mc-soi/8f89e2e6a7ed49e04bcb

A #if (PG_VERSION_NUM >= 90500) might be required to make this code also compile with earlier versions.

**Comment by GeoffMontee** [comment]
Thanks for the patch, @mc-soi!

I've made the change, but maintained compatibility with older versions: https://github.com/GeoffMontee/tds_fdw/commit/2b09f99ac964369764a5d43419c3f9c788753087

I've confirmed that this builds on PostgreSQL 9.4 and 9.5.

**Comment by GeoffMontee** [comment]
Fixed in v1.0.4.
