### ISSUE TITLE
Trailing spaces should not be removed

### ISSUE THREAD

**Issue by tskenb** [GeoffMontee/tds_fdw#35]
Currently they are.

It isn't documented, but the source code to freetds's dbconvert() function shows that a destlen of -1 removes trailing spaces, while a destlen of -2 doesn't, but is the same in other respects.

Here is a [patch that simply uses -2 instead of -1](https://gist.github.com/tskenb/9ca5d50a680149d7d1c8).

**Comment by GeoffMontee** [comment]
Thanks again for the patch, @tskenb!

Fixed: https://github.com/GeoffMontee/tds_fdw/commit/6fd9db53ff1bbeddc21a3e61c7359d8d449b3dc4

**Comment by GeoffMontee** [comment]
Fixed in 1.0.6.
