### ISSUE TITLE
Handle tables with more than INT_MAX rows

### ISSUE THREAD

**Issue by tskenb** [GeoffMontee/tds_fdw#36]
Currently the num rows estimate is retrieved as an int, which freetds rejects when the server's estimate (a four byte float in mssql) is more than approximately INT_MAX.

[Here is a patch](https://gist.github.com/tskenb/b584406a0ce42046d595) that retrieves the value as a double.  In all of its usages later the estimate is converted to a double anyway, so this should cause no harm.

**Comment by GeoffMontee** [comment]
Thanks for the patch, @tskenb!

Fixed: https://github.com/GeoffMontee/tds_fdw/commit/95aa2b8d343be26713513e44502574145e161e6e

**Comment by GeoffMontee** [comment]
Fixed in 1.0.6.
