### ISSUE TITLE
can i update foreign table?

### ISSUE THREAD

**Issue by alfarioekaputra** [GeoffMontee/tds_fdw#39]
hello, can i update the foreign table?

i try with 
```
update foreign_table set field=1 
```

and i get the error 

```
ERROR: cannot update foreign table "foregin_table"
SQL state: 0A000
```

thanks

**Comment by tskenb** [comment]
I believe I can answer this one: tds_fdw is read-only at this point, so no, you can't yet update a foreign table.

**Comment by GeoffMontee** [comment]
Hi @Rio,

Write operations are not supported by tds_fdw yet. Please subscribe to issue #9 if you would like to be notified when that feature is ready.

**Comment by ykseiljon** [comment]
sorry, I know this issue is closed. 
I want to be notified when that feature is ready too.

**Comment by GeoffMontee** [comment]
Hi @ykseiljon,

If you would like to be notified when the feature is ready, then please subscribe to issue #9.

**Comment by ykseiljon** [comment]
excuse me, but, how do it, just typing +1???

**Comment by GeoffMontee** [comment]
Adding a comment to the issue (such as commenting "+1")  should subscribe you to it, but there's also a "Subscribe" button on the right side of the page.
