### ISSUE TITLE
Extension update

### ISSUE THREAD

**Issue by ohvitorino** [GeoffMontee/tds_fdw#41]
Hi,

Is it sufficient to install a new version just by compiling and installing, or do I also need to run 
`ALTER EXTENSION tds_fdw UPDATE` on my server?

I tried to run the `ALTER EXTENSION`, but I get the following error:
> extension "tds_fdw" has no update path from version "1.0.1" to version "1.0.6"

Thanks!

**Comment by GeoffMontee** [comment]
There's no need to run `ALTER EXTENSION tds_fdw UPDATE` for any of the updates that have been released so far. All you need to do to upgrade is compile the new version of the extension, install it, and then restart PostgreSQL.

**Comment by ohvitorino** [comment]
Ok, thanks @GeoffMontee

**Comment by GeoffMontee** [comment]
No problem. Let me know if you run into any other issues.

**Comment by donnorman** [comment]
Hello,

I tried updating from 1.0.3 to 1.0.6, the compile and install went fine (the date on the module in the lib folder is the date of the install), but \dx still shows v1.0.3 running after restarting PostgreSQL.

Is there something else that I can try to get the latest version to load?

Thanks!
