### ISSUE TITLE
Query foreign table, got error messages

### ISSUE THREAD

**Issue by hendrix0623** [GeoffMontee/tds_fdw#56]
Dear Geoff Montee, 

client : red hat linux / postgreSQL 9.4
target: windows server 2012 R2 /  SQL server 2014

After finishing installation, I create foreign table with following command. No error occurs.

    create extension tds_fdw;
    CREATE SERVER mssql_svr
        FOREIGN DATA WRAPPER tds_fdw
        OPTIONS (servername 'mssql', port '1433', database 'A00PT');
    
    CREATE USER MAPPING FOR postgres SERVER mssql_svr OPTIONS (username 'a00ptapio', password 'xxxxxxx');
    
        CREATE FOREIGN TABLE mssql_table (
        CODE char(5))
        SERVER mssql_svr
        OPTIONS (query 'SELECT CODE FROM dbo.CODE', row_estimate_method 'showplan_all');

 
When I try to query foreign table, got error messages as below.  

    select * from mssql_table;
    ----------------------------------------------------------------
    ERROR:  DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14
    ********** Error **********
    ERROR: DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14
    SQL state: HV00L

Check pg error code "HV00L" means  "fdw_unable_to_create_execution", but rare information from internet. 
In this case :
1. Client sessions are established (I examined by sp_who and SQL profiler from MS windows server). 
2. Connect MSSQL by "tsql" seems to be success (please see below ).

I'm not sure what kinda problem to cause that... do you any idea ? 
Very thanks ^^

**freetds.conf**

    [global]
            # TDS protocol version
    ;       tds version = 8.0
    
            # Whether to write a TDSDUMP file for diagnostic purposes
            # (setting this to /tmp is insecure on a multi-user system)
    ;       dump file = /tmp/freetds.log
    ;       debug flags = 0xffff
    
            # Command and connection timeouts
    ;       timeout = 10
    ;       connect timeout = 10
    
            # If you get out-of-memory errors, it may mean that your client
            # is trying to allocate a huge buffer for a TEXT field.
            # Try setting 'text size' to a more reasonable limit
            text size = 64512
            client charset = UTF-8
    # A typical Sybase server
    [egServer50]
            host = symachine.domain.com
            port = 5000
            tds version = 5.0
    
    # A typical Microsoft server
    [mssql]
            host = 10.x.x.1
            port = 1433
            tds version = 8.0

**manual connect with output log**

    $ TDSDUMPCONFIG=stdout  TDSDUMP=stdout tsql -S mssql -U a00ptapio -D A00PT -P xxxxxxx

    log.c:167:Starting log file for FreeTDS 0.95.76
            on 2016-01-14 17:12:30 with debug flags 0x4fff.
    config.c:168:Getting connection information for [mssql].
    config.c:172:Attempting to read conf files.
    config.c:353:... $FREETDSCONF not set.  Trying $FREETDS/etc.
    config.c:366:... $FREETDS not set.  Trying $HOME.
    config.c:292:Could not open '/opt/PostgreSQL/9.4/.freetds.conf' ((.freetds.conf)).
    config.c:296:Found conf file '/usr/local/etc/freetds.conf' (default).
    config.c:495:Looking for section global.
    config.c:554:   Found section global.
    config.c:557:Got a match.
    config.c:580:   text size = '64512'
    config.c:580:   client charset = 'UTF-8'
    config.c:635:tds_parse_conf_section: client charset is UTF-8.
    config.c:554:   Found section egserver50.
    config.c:554:   Found section mssql.
    config.c:568:   Reached EOF
    config.c:495:Looking for section mssql.
    config.c:554:   Found section global.
    config.c:554:   Found section egserver50.
    config.c:554:   Found section mssql.
    config.c:557:Got a match.
    config.c:580:   host = '10.x.x.1'
    config.c:617:Found host entry 10.x.x.1
    config.c:620:IP addr is 10.x.x.1.
    config.c:620:IP addr is 10.x.x.1.
    config.c:620:IP addr is 10.x.x.1.
    config.c:580:   port = '1433'
    config.c:580:   tds version = '8.0'
    config.c:886:Setting tds version to 8.0 (0x701).
    config.c:568:   Reached EOF
    config.c:300:Success: [mssql] defined in /usr/local/etc/freetds.conf.
    config.c:765:Setting 'dump_file' to 'stdout' from $TDSDUMP.
    config.c:213:Final connection parameters:
    config.c:214:            server_name = mssql
    config.c:215:       server_host_name = 10.x.x.1
    config.c:218:                ip_addr = 10.x.x.1
    config.c:218:                ip_addr = 10.x.x.1
    config.c:218:                ip_addr = 10.x.x.1
    config.c:223:          instance_name =
    config.c:224:                   port = 1433
    config.c:225:          major_version = 7
    config.c:226:          minor_version = 1
    config.c:227:             block_size = 0
    config.c:228:               language = us_english
    config.c:229:         server_charset = iso_1
    config.c:230:        connect_timeout = 0
    config.c:231:       client_host_name = RH64
    config.c:232:         client_charset = UTF-8
    config.c:233:              use_utf16 = 0
    config.c:234:               app_name = TSQL
    config.c:235:              user_name = a00ptapio
    config.c:238:                library = TDS-Library
    config.c:239:              bulk_copy = 0
    config.c:240:      suppress_language = 0
    config.c:241:          encrypt level = 0
    config.c:242:          query_timeout = 0
    config.c:245:               database =
    config.c:246:              dump_file = stdout
    config.c:247:            debug_flags = 0
    config.c:248:              text_size = 64512
    config.c:249:     emul_little_endian = 0
    config.c:250:      server_realm_name =
    config.c:251:             server_spn =
    config.c:252:                 cafile =
    config.c:253:                crlfile =
    config.c:254:     check_ssl_hostname = 1
    log.c:167:Starting log file for FreeTDS 0.95.76
            on 2016-01-14 17:12:30 with debug flags 0x4fff.
    locale is "en_US.UTF-8"
    locale charset is "UTF-8"
    using default charset "UTF-8"
    Setting A00PT as default database in login packet
    iconv.c:328:tds_iconv_open(0x22303b0, UTF-8)
    iconv.c:187:local name for ISO-8859-1 is ISO-8859-1
    iconv.c:187:local name for UTF-8 is UTF-8
    iconv.c:187:local name for UCS-2LE is UCS-2LE
    iconv.c:187:local name for UCS-2BE is UCS-2BE
    iconv.c:346:setting up conversions for client charset "UTF-8"
    iconv.c:348:preparing iconv for "UTF-8" <-> "UCS-2LE" conversion
    iconv.c:395:preparing iconv for "ISO-8859-1" <-> "UCS-2LE" conversion
    iconv.c:400:tds_iconv_open: done
    net.c:202:Connecting to 10.x.x.1 port 1433 (TDS version 7.1)
    net.c:275:tds_open_socket: connect(2) returned "Operation now in progress"
    net.c:314:tds_open_socket() succeeded
    packet.c:740:Sending packet
    0000 12 01 00 34 00 00 00 00-00 00 15 00 06 01 00 1b |...4.... ........|
    0010 00 01 02 00 1c 00 0c 03-00 28 00 04 ff 08 00 01 |........ .(......|
    0020 55 00 00 02 4d 53 53 51-4c 53 65 72 76 65 72 00 |U...MSSQ LServer.|
    0030 c1 2e 00 00            -                        |....|
    
    packet.c:639:Received packet
    0000 04 01 00 25 00 00 01 00-00 00 15 00 06 01 00 1b |...%.... ........|
    0010 00 01 02 00 1c 00 01 03-00 1d 00 00 ff 0c 00 10 |........ ........|
    0020 04 00 00 02 00         -                        |.....|
    
    login.c:1106:detected flag 2
    login.c:852:quietly sending TDS 7+ login packet
    token.c:326:tds_process_login_tokens()
    packet.c:639:Received packet
    0000 04 01 01 5f 00 4a 01 00-e3 19 00 01 05 41 00 30 |..._.J.. .....A.0|
    0010 00 30 00 50 00 54 00 06-6d 00 61 00 73 00 74 00 |.0.P.T.. m.a.s.t.|
    0020 65 00 72 00 ab 48 00 45-16 00 00 02 00 13 00 f2 |e.r..H.E ........|
    0030 5d 07 5c c7 8c 99 65 ab-5e 67 51 b9 5b 8a 8b f4 |].\...e. ^gQ.[...|
    0040 66 ba 70 20 00 27 00 41-00 30 00 30 00 50 00 54 |f.p .'.A .0.0.P.T|
    0050 00 27 00 02 30 0b 46 00-45 00 4e 00 43 00 5f 00 |.'..0.F. E.N.C._.|
    0060 54 00 45 00 53 00 54 00-44 00 42 00 00 01 00 e3 |T.E.S.T. D.B.....|
    0070 08 00 07 05 04 04 d0 00-00 00 e3 17 00 02 0a 75 |........ .......u|
    0080 00 73 00 5f 00 65 00 6e-00 67 00 6c 00 69 00 73 |.s._.e.n .g.l.i.s|
    0090 00 68 00 00 ab 70 00 47-16 00 00 01 00 27 00 43 |.h...p.G .....'.C|
    00a0 00 68 00 61 00 6e 00 67-00 65 00 64 00 20 00 6c |.h.a.n.g .e.d. .l|
    00b0 00 61 00 6e 00 67 00 75-00 61 00 67 00 65 00 20 |.a.n.g.u .a.g.e. |
    00c0 00 73 00 65 00 74 00 74-00 69 00 6e 00 67 00 20 |.s.e.t.t .i.n.g. |
    00d0 00 74 00 6f 00 20 00 75-00 73 00 5f 00 65 00 6e |.t.o. .u .s._.e.n|
    00e0 00 67 00 6c 00 69 00 73-00 68 00 2e 00 0b 46 00 |.g.l.i.s .h....F.|
    00f0 45 00 4e 00 43 00 5f 00-54 00 45 00 53 00 54 00 |E.N.C._. T.E.S.T.|
    0100 44 00 42 00 00 01 00 ad-36 00 01 71 00 00 01 16 |D.B..... 6..q....|
    0110 4d 00 69 00 63 00 72 00-6f 00 73 00 6f 00 66 00 |M.i.c.r. o.s.o.f.|
    0120 74 00 20 00 53 00 51 00-4c 00 20 00 53 00 65 00 |t. .S.Q. L. .S.e.|
    0130 72 00 76 00 65 00 72 00-00 00 00 00 0c 00 10 04 |r.v.e.r. ........|
    0140 e3 13 00 04 04 34 00 30-00 39 00 36 00 04 34 00 |.....4.0 .9.6..4.|
    0150 30 00 39 00 36 00 fd 00-00 00 00 00 00 00 00    |0.9.6... .......|
    
    token.c:335:looking for login token, got  e3(ENVCHANGE)
    token.c:115:tds_process_default_tokens() marker is e3(ENVCHANGE)
    token.c:335:looking for login token, got  ab(INFO)
    token.c:115:tds_process_default_tokens() marker is ab(INFO)
    token.c:2344:tds_process_msg() reading message 5701 from server
    token.c:2416:tds_process_msg() calling client msg handler
    token.c:2429:tds_process_msg() returning TDS_SUCCESS
    token.c:335:looking for login token, got  e3(ENVCHANGE)
    token.c:115:tds_process_default_tokens() marker is e3(ENVCHANGE)
    token.c:2178:tds_process_env_chg(): 5 bytes of collation data received
    token.c:2179:tds->conn->collation was
    0000 00 00 00 00 00         -                        |.....|
    
    iconv.c:796:setting server single-byte charset to "CP950"
    token.c:2189:tds->conn->collation now
    0000 04 04 d0 00 00         -                        |.....|
    
    token.c:335:looking for login token, got  e3(ENVCHANGE)
    token.c:115:tds_process_default_tokens() marker is e3(ENVCHANGE)
    token.c:335:looking for login token, got  ab(INFO)
    token.c:115:tds_process_default_tokens() marker is ab(INFO)
    token.c:2344:tds_process_msg() reading message 5703 from server
    token.c:2416:tds_process_msg() calling client msg handler
    token.c:2429:tds_process_msg() returning TDS_SUCCESS
    token.c:335:looking for login token, got  ad(LOGINACK)
    token.c:373:server reports TDS version 71.0.0.1
    token.c:375:Product name for 0x71000001 is 2000 SP1
    token.c:407:Product version 8C001004
    token.c:335:looking for login token, got  e3(ENVCHANGE)
    token.c:115:tds_process_default_tokens() marker is e3(ENVCHANGE)
    token.c:2235:changing block size from 4096 to 4096
    token.c:335:looking for login token, got  fd(DONE)
    token.c:115:tds_process_default_tokens() marker is fd(DONE)
    token.c:2080:tds_process_end: more_results = 0
                    was_cancelled = 0
                    error = 0
                    done_count_valid = 0
    token.c:2097:                rows_affected = 0
    token.c:2100:tds_process_end() state set to TDS_IDLE
    token.c:439:tds_process_login_tokens() returning TDS_SUCCESS
    mem.c:648:tds_free_all_results()
    util.c:165:Changed query state from IDLE to WRITING
    util.c:165:Changed query state from WRITING to PENDING
    packet.c:740:Sending packet
    0000 01 01 00 2e 00 00 00 00-73 00 65 00 74 00 20 00 |........ s.e.t. .|
    0010 74 00 65 00 78 00 74 00-73 00 69 00 7a 00 65 00 |t.e.x.t. s.i.z.e.|
    0020 20 00 36 00 34 00 35 00-31 00 32 00 20 00       | .6.4.5. 1.2. .|
    
    token.c:549:tds_process_tokens(0x22303b0, 0x7fffe1bcc29c, 0x7fffe1bcc298, 0x100)
    util.c:165:Changed query state from PENDING to READING
    packet.c:639:Received packet
    0000 04 01 00 11 00 4a 01 00-fd 00 00 be 00 00 00 00 |.....J.. ........|
    0010 00                     -                        |.|
    
    token.c:564:processing result tokens.  marker is  fd(DONE)
    token.c:2080:tds_process_end: more_results = 0
                    was_cancelled = 0
                    error = 0
                    done_count_valid = 0
    token.c:2097:                rows_affected = 0
    token.c:2100:tds_process_end() state set to TDS_IDLE
    util.c:165:Changed query state from READING to IDLE
    util.c:83:logic error: cannot change query state from IDLE to PENDING
    util.c:165:Changed query state from IDLE to IDLE
    token.c:549:tds_process_tokens(0x22303b0, 0x7fffe1bcc29c, 0x7fffe1bcc298, 0x100)
    token.c:552:tds_process_tokens() state is COMPLETED
    1>

**Comment by GeoffMontee** [comment]
> ERROR:  DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14

This error message doesn't actually tell us what the problem was.

Can you please try setting `msg_handler` for the [foreign server](https://github.com/GeoffMontee/tds_fdw/blob/master/ForeignServerCreation.md) to `'notice'` to see if that gives us more detailed information?

Does your PostgreSQL log provide any more information?

Depending on how old your version of FreeTDS is, I think `tds version = 8.0` may not be valid. It might be worth trying to use 7.0, 7.1, or 7.2.

**Comment by hendrix0623** [comment]
Dear Geoff Montee, 

After setting up msg_handler, the error message tells what happened...the privilege wasn't properly grant. After object privilege modified, then tds_fdw query works~ 

 Thank you very much !!

    NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: 已將資料庫內容變更為 'A00PT'。, Server: FENC_TESTDB, Process: , Line: 1, Level: 0
    NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: FENC_TESTDB, Process: , Line: 1, Level: 0
    NOTICE:  DB-Library notice: Msg #: 229, Msg state: 5, Msg: The SELECT permission was denied on the object 'CODE', database 'A00PT', schema 'dbo'., Server: FENC_TESTDB, Process: , Line: 1, Level: 14


Thanks for your

**Comment by GeoffMontee** [comment]
Awesome! I'm glad to hear that it's working now.
