### ISSUE TITLE
Does updating the remote table (mssql table) is possible with tds_fdw using the postgresql (foreign table)

### ISSUE THREAD

**Issue by gkchinna** [GeoffMontee/tds_fdw#57]
Hi ,

I would like to know whether tds_fdw have similar functionalities as postgres_fdw? In particular DML through foreign table is possible or not and reflect the remote table?

**Comment by GeoffMontee** [comment]
Hi @gkchinna,

tds_fdw does not yet support write operations, such as insert, update, and delete. That feature is being tracked as issue #9.

**Comment by gkchinna** [comment]
Hi Thank you very much for the confirmation.

On Sun, Jan 24, 2016 at 7:08 AM, Geoff Montee <notifications@github.com>
wrote:

> Hi @gkchinna <https://github.com/gkchinna>,
>
> tds_fdw does not yet support write operations, such as insert, update, and
> delete. That feature is being tracked as issue #9
> <https://github.com/GeoffMontee/tds_fdw/issues/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoffMontee/tds_fdw/issues/57#issuecomment-174241218>.
>



-- 

*-regards *

Gowtham Kumar


*TIME*

The future is something which everyone reaches at the rate of sixty minutes
an hour , whatever he does , whoever he is.

**Comment by GeoffMontee** [comment]
No problem! Thanks for your interest in tds_fdw.
